//
// Module Image_Watermarking_Project_lib.Amba_Bus_controller.Amba_Bus_controller
//
// Created:
//          by - Yakir.UNKNOWN (YAKIR-PC)
//          at - 20:03:40 28/11/2020
//
// Generated by Mentor Graphics' HDL Designer(TM) 2018.2 (Build 19)
//

`resetall
`timescale 1ns/10ps
module Amba_Bus_controller #(
   // synopsys template
   parameter amba_word       = 16,  //word size
   parameter amba_addr_depth = 20   //address size
)
( 
   // Port Declarations
   input   wire                           penable, 
   input   wire    [amba_word-1:0]        prdata_in, 
   input   wire                           psel, 
   input   wire                           pwrite, 
   output  wire    [amba_word-1:0]        prdata, 
   output  wire                           w_ena
);


// Internal Declarations


// Local declarations

// Internal signal declarations


// Instances 
WriteandRead_no_wait U_0( 
   .PSEL      (psel), 
   .PWRITE    (pwrite), 
   .P_rdata_in (prdata_in), 
   .P_enable   (penable), 
   .Wena     (w_ena), 
   .PRDATA    (prdata)
); 


endmodule // Amba_Bus_controller

