//
// Module Image_Watermarking_Project_lib.BlockTransmition.struct
//
// Created:
//          by - Yakir.UNKNOWN (YAKIR-PC)
//          at - 22:24:35 15/12/2020
//
// Generated by Mentor Graphics' HDL Designer(TM) 2018.2 (Build 19)
//

`resetall
`timescale 1ns/10ps
module BlockTransmition #(
   // synopsys template
   parameter Data_Depth      = 8,
   parameter Max_block_size  = 5184,
   parameter amba_addr_depth = 20,
   parameter amba_word       = 16
)
( 
   // Port Declarations
   input   wire    [amba_word-1:0]        Data_in, 
   input   wire                           FinishCalc, 
   input   wire                           clk, 
   input   wire                           rst, 
   input   wire                           start, 
   output  wire                           LastPrimBlock, 
   output  wire                           LastWaterBlock, 
   output  wire    [Data_Depth-1:0]       P_pixel, 
   output  wire    [amba_addr_depth-1:0]  PixelAddress, 
   output  wire    [Data_Depth-1:0]       W_pixel, 
   output  wire    [6:0]                  alpha_out, 
   output  wire    [5:0]                  beta_out, 
   output  wire    [9:0]                  blockSize, 
   output  wire                           start_calc_iw_k
);


// Internal Declarations


// Local declarations

// Internal signal declarations


// Instances 
BlockStorage #(20,16,5184,8) U_0( 
   .Data_in         (Data_in), 
   .Finish_Calc      (FinishCalc), 
   .LastPrimBlock   (LastPrimBlock), 
   .LastWaterBlock  (LastWaterBlock), 
   .Ppixel         (P_pixel), 
   .PixelAddress    (PixelAddress), 
   .Wpixel         (W_pixel), 
   .alpha_out       (alpha_out), 
   .beta_out        (beta_out), 
   .Block_Size       (blockSize), 
   .clk             (clk), 
   .rst             (rst), 
   .start           (start), 
   .StartCalcIWk (start_calc_iw_k)
); 


endmodule // BlockTransmition

