//
// Module Image_Watermarking_Project_lib.Registers_Bank.struct
//
// Created:
//          by - Yakir.UNKNOWN (YAKIR-PC)
//          at - 11:31:39 13/12/2020
//
// Generated by Mentor Graphics' HDL Designer(TM) 2018.2 (Build 19)
//

`resetall
`timescale 1ns/10ps
module Registers_Bank #(
   // synopsys template
   parameter amba_word       = 16,
   parameter amba_addr_depth = 20,
   parameter Data_Depth      = 8
)
( 
   // Port Declarations
   input   wire    [amba_addr_depth-1:0]  PADDR, 
   input   wire                           clk, 
   input   wire    [amba_word-1:0]        input_data, 
   input   wire    [amba_addr_depth-1:0]  read_pixel_addr, 
   input   wire                           rst, 
   input   wire                           w_ena, 
   output  wire    [amba_word-1:0]        data_out, 
   output  wire                           start
);


// Internal Declarations


// Local declarations

// Internal signal declarations


// Instances 
Reg_File #(20,16,8) U_0( 
   .PADDR           (PADDR), 
   .clk             (clk), 
   .DataOut        (data_out), 
   .input_data      (input_data), 
   .read_pixel_addr (read_pixel_addr), 
   .rst             (rst), 
   .start           (start), 
   .w_ena           (w_ena)
); 


endmodule // Registers_Bank

