//
// Module Image_Watermarking_Project_lib.Visible_Watermarking.struct
//
// Created:
//          by - Yakir.UNKNOWN (YAKIR-PC)
//          at - 23:55:38 15/12/2020
//
// Generated by Mentor Graphics' HDL Designer(TM) 2018.2 (Build 19)
//

`resetall
`timescale 1ns/10ps
module Visible_Watermarking #(
   // synopsys template
   parameter amba_word       = 16,
   parameter amba_addr_depth = 20,
   parameter Data_Depth      = 8,
   parameter Max_block_size  = 5184
)
( 
   // Port Declarations
   input   wire    [amba_addr_depth-1:0]  PADDR, 
   input   wire                           PENABLE, 
   input   wire                           PSEL, 
   input   wire    [amba_word-1:0]        PWDATA, 
   input   wire                           PWRITE, 
   input   wire                           clk, 
   input   wire                           rst, 
   output  wire                           Image_Done, 
   output  wire    [amba_word-1:0]               PRDATA, 
   output  wire    [Data_Depth-1:0]       Pixel_Data, 
   output  wire                           new_pixel
);


// Internal Declarations


// Local declarations

// Internal signal declarations
wire                        Finish_calc;
wire                        LastPrimBlock;
wire                        LastWaterBlock;
wire  [Data_Depth-1:0]      P_pixel;
wire  [amba_addr_depth-1:0] PixelAddress;
wire  [Data_Depth-1:0]      W_pixel;
wire  [6:0]                 alpha_out;
wire  [5:0]                 beta_out;
wire  [9:0]                 blockSize;
wire  [amba_word-1:0]       data_out;
wire                        dout;
wire  [amba_word-1:0]              prdata;
wire                        start;
wire                        start_calc_iw_k;
wire                        w_ena;


// Instances 
Amba_Bus_controller U_0( 
   .penable   (PENABLE), 
   .prdata_in (PWDATA), 
   .psel      (PSEL), 
   .pwrite    (PWRITE), 
   .prdata    (prdata), 
   .w_ena     (w_ena)
); 

BlockTransmition U_4( 
   .Data_in         (data_out), 
   .FinishCalc      (Finish_calc), 
   .clk             (clk), 
   .rst             (rst), 
   .start           (start), 
   .LastPrimBlock   (LastPrimBlock), 
   .LastWaterBlock  (LastWaterBlock), 
   .P_pixel         (P_pixel), 
   .PixelAddress    (PixelAddress), 
   .W_pixel         (W_pixel), 
   .alpha_out       (alpha_out), 
   .beta_out        (beta_out), 
   .blockSize       (blockSize), 
   .start_calc_iw_k (start_calc_iw_k)
); 

Registers_Bank U_3( 
   .PADDR           (PADDR), 
   .clk             (clk), 
   .input_data      (PWDATA), 
   .read_pixel_addr (PixelAddress), 
   .rst             (rst), 
   .w_ena           (w_ena), 
   .data_out        (data_out), 
   .start           (start)
); 

eq_imp U_5( 
   .P_pixel         (P_pixel), 
   .W_pixel         (W_pixel), 
   .alpha           (alpha_out), 
   .beta            (beta_out), 
   .clk             (clk), 
   .rst             (rst), 
   .M               (blockSize), 
   .start_calc_iw_k (start_calc_iw_k), 
   .Last_Prim_Block   (LastPrimBlock), 
   .Last_Water_Block  (LastWaterBlock), 
   .FinishCalc     (Finish_calc), 
   .iwPixel        (Pixel_Data), 
   .Image_Done      (Image_Done), 
   .new_pixel       (new_pixel)
); 


// ModuleWare code(v1.12) for instance 'U_6' of 'and1'
assign PRDATA = prdata & {16{dout}};

// ModuleWare code(v1.12) for instance 'U_1' of 'inv'
assign dout = ~rst;

endmodule // Visible_Watermarking

